### ISSUE TITLE
Разработка DeleteFilebyWorld.cs

### ISSUE THREAD

**Issue by IsMoDex** [PI21b-group-dynamics/DFBW_group2#2]
Данный класс DeleteFilebyWorld.cs, представляет основной класс содержащий алгоритма поиска и удаления фалов содержащих с в своем названии или данных слово или фразу переданную в функцию для старта алгоритма.

**Comment by GeorgeBubnov** [comment]
Добавь в справку описание задачи, которую реализует основной блок программы.

**Comment by GeorgeBubnov** [comment]
И реализуй возможность выбора директории с помощью диалогового окна.

**Comment by IsMoDex** [comment]
Добавлено

**Comment by GeorgeBubnov** [comment]
Принял.
