### ISSUE TITLE
Разработка DeleteFile_by_WordForm.cs

### ISSUE THREAD

**Issue by IsMoDex** [PI21b-group-dynamics/DFBW_group2#3]
Данный класс представляет собой первоначальную форму для взаимодействия тестировщика и программы.

**Comment by GeorgeBubnov** [comment]
Реализуй возможность выбора директории с помощью диалогового окна.

**Comment by IsMoDex** [comment]
Выполнено!

**Comment by GeorgeBubnov** [comment]
Хорошая работа.
